[package]
name = "acumen"
version = "0.1.0"
edition = "2024"

[lints.rust]
unsafe_code = "deny"

[lints.clippy]
pedantic = "warn"

[dependencies]
crossterm = "0.29.0"
glob = "0.3.2"
ratatui = "0.29.0"

[dependencies.uuid]
version = "1.17.0"
features = ["v4"]
